### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by jsonbaozi** [jsonbaozi/samsung-challenge#1]
![screenshot_20180618-003552_expo](https://user-images.githubusercontent.com/33274656/41523801-1ba6d7ce-7290-11e8-831a-7a02803260a3.jpg)
![screenshot_20180618-003601_expo](https://user-images.githubusercontent.com/33274656/41523802-1bc2f79c-7290-11e8-883e-488369a871dd.jpg)

**Comment by YZhenY** [comment]
wowoz
